# Синхронизация UI в mobile/ для flet build apk
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$dst = Join-Path $root "mobile\frontend"
$src = Join-Path $root "frontend"

if (Test-Path $dst) { Remove-Item -Recurse -Force $dst }
New-Item -ItemType Directory -Path $dst | Out-Null
New-Item -ItemType Directory -Path (Join-Path $dst "assets") | Out-Null

$files = @(
  "__init__.py",
  "app.py",
  "assests.py",
  "live_call_flet.py",
  "phone_utils.py",
  "labels.py"
)
foreach ($f in $files) {
  Copy-Item (Join-Path $src $f) (Join-Path $dst $f) -Force
}
Copy-Item (Join-Path $src "assets\*") (Join-Path $dst "assets") -Recurse -Force -ErrorAction SilentlyContinue

# API URL для телефона (tunnel на uvicorn :8000) — без секретов
$api = $env:DEMO_API_URL
if (-not $api) { $api = $env:DEMO_WEB_URL }
if (-not $api) {
  $envFile = Join-Path $root ".env"
  if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
      if ($_ -match '^\s*DEMO_API_URL\s*=\s*(.+)$') { $api = $Matches[1].Trim().Trim('"') }
      elseif ($_ -match '^\s*DEMO_WEB_URL\s*=\s*(.+)$' -and -not $api) { $api = $Matches[1].Trim().Trim('"') }
    }
  }
}
$api = ($api -replace '/$', '')
if (-not $api) { $api = "http://127.0.0.1:8000" }
@"
# auto-generated by scripts/prepare_mobile.ps1 — не коммитить секреты
DEFAULT_API_BASE = "$api"
"@ | Set-Content -Encoding utf8 (Join-Path $root "mobile\api_defaults.py")
Write-Host "mobile/frontend synced; DEFAULT_API_BASE=$api"
